### ISSUE TITLE
I'd like to join this project's community

### ISSUE THREAD

**Issue by dworthen2** [gov4git/dworthen-project-repo-v2#5]
### Your public repo

https://github.com/dworthen2/gov4git-identity-public.git

### Your public branch

main

**Comment by dworthen** [comment]
Approve

**Comment by dworthen** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Friday, 12-Jan-24 22:26:09 UTC` by Gov4Git `dev`

@dworthen2 was added to the community.

**Comment by dworthen** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Tuesday, 16-Jan-24 15:54:01 UTC` by Gov4Git `dev`

@dworthen2 was added to the community.

**Comment by dworthen** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Wednesday, 17-Jan-24 14:31:52 UTC` by Gov4Git `dev`

@dworthen2 was added to the community.
